// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkCErlIzzMMXgM5BfZ0PT-U08gB7FwB98',
    appId: '1:679249631722:web:8de63f89f534c88393fa93',
    messagingSenderId: '679249631722',
    projectId: 'go-app-c5f37',
    authDomain: 'go-app-c5f37.firebaseapp.com',
    storageBucket: 'go-app-c5f37.firebasestorage.app',
    measurementId: 'G-S88GMG1W8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2UXgYY9IAHb7ompvxdKZqQzxY2hvnKk',
    appId: '1:679249631722:android:25b598937f5cdea493fa93',
    messagingSenderId: '679249631722',
    projectId: 'go-app-c5f37',
    storageBucket: 'go-app-c5f37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhMwmNhnGc8Zh-Eykwx2Rpxu90kAhqkZs',
    appId: '1:679249631722:ios:71f446fd7adedd0c93fa93',
    messagingSenderId: '679249631722',
    projectId: 'go-app-c5f37',
    storageBucket: 'go-app-c5f37.firebasestorage.app',
    iosClientId: '679249631722-6sbo08b5d4arm13pq9urcpaeenokcbfg.apps.googleusercontent.com',
    iosBundleId: 'com.go.go',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhMwmNhnGc8Zh-Eykwx2Rpxu90kAhqkZs',
    appId: '1:679249631722:ios:71f446fd7adedd0c93fa93',
    messagingSenderId: '679249631722',
    projectId: 'go-app-c5f37',
    storageBucket: 'go-app-c5f37.firebasestorage.app',
    iosClientId: '679249631722-6sbo08b5d4arm13pq9urcpaeenokcbfg.apps.googleusercontent.com',
    iosBundleId: 'com.go.go',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkCErlIzzMMXgM5BfZ0PT-U08gB7FwB98',
    appId: '1:679249631722:web:060f6e9441ba441993fa93',
    messagingSenderId: '679249631722',
    projectId: 'go-app-c5f37',
    authDomain: 'go-app-c5f37.firebaseapp.com',
    storageBucket: 'go-app-c5f37.firebasestorage.app',
    measurementId: 'G-DFX5YZYHKR',
  );

}